version: '3.4'

services:
  caddy:
    container_name: adguard
    image: adguard/adguardhome:latest
    restart: unless-stopped
    volumes:
      - "adguard_work:/opt/adguardhome/work"
      - "/etc/adguard/:/opt/adguardhome/conf/"
    ports:
      - "192.168.150.1:53:53/udp"
      - "192.168.150.1:53:53/tcp"
    networks:
      - caddy

volumes:
  adguard_work:

networks:
  caddy:
    external: true