- hosts: all
  name: Deploy WireGuard to Host
  tags: [always]
  become: true
  tasks:
    - name: Include vault vars
      ansible.builtin.include_vars:
        file: vault_vars.yml

    - name: Install WireGuard
      ansible.builtin.apt:
        name:
          - wireguard-dkms
          - wireguard-tools
        state: present
      notify:
        - Reboot to load kernel modules and start Wireguard

    - name: Copy the WireGuard 0 configuration
      ansible.builtin.template:
        src: wg0.conf
        dest: /etc/wireguard/wg0.conf
        mode: 0600

    - name: Enable IP Forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true
        state: present
        reload: true

    - name: Enable Wireguard 0
      ansible.builtin.systemd:
        name: wg-quick@wg0.service
        enabled: true

    - name: Allow wireguard 0 through UFW
      community.general.ufw:
        rule: allow
        port: 51820
        proto: udp

  handlers:
    - name: Reboot to load kernel modules and start Wireguard
      ansible.builtin.reboot:
