- hosts: all
  name: Create containers
  tags: [always]
  become: true
  tasks:
    - name: Include vault vars
      ansible.builtin.include_vars:
        file: vault_vars.yml

    - name: Create docker compose configuration directory
      ansible.builtin.file:
        path: /etc/compose
        state: directory
        mode: '0755'

    - name: Create caddy compose configuration directory
      ansible.builtin.file:
        path: /etc/compose/caddy
        state: directory
        mode: '0755'

    - name: Copy the compose file
      ansible.builtin.template:
        src: docker-compose.yaml
        dest: /etc/compose/docker-compose.yaml
        mode: 0600

    - name: Copy the caddy dockerfile
      ansible.builtin.copy:
        src: Dockerfile.caddy
        dest: /etc/compose/caddy/Dockerfile
        mode: 0644

    - name: Create vaultwarden volume
      community.docker.docker_volume:
        name: vaultwarden_vol

    - name: Create adguard etc directory
      ansible.builtin.file:
        path: /etc/adguard
        state: directory
        mode: '0755'

    - name: Copy the adguard config file
      ansible.builtin.template:
        src: adguard.yaml
        dest: /etc/adguard/AdGuardHome.yaml
        mode: 0600

    - name: Create caddy configuration directory
      ansible.builtin.file:
        path: /etc/caddy
        state: directory
        mode: '0755'

    - name: Copy the Caddyfile
      ansible.builtin.copy:
        src: Caddyfile
        dest: /etc/caddy/Caddyfile
        mode: 0644

    - name: Build and start containers
      community.docker.docker_compose:
        project_src: /etc/compose/
        build: true
        state: present
