- hosts: all
  name: Perform Initial Setup and Hardening
  tags: [always]
  become: true
  tasks:
    - name: Include vault vars
      ansible.builtin.include_vars:
        file: vault_vars.yml

    - name: Install packages
      ansible.builtin.apt:
        name:
          - ufw
          - vim
          - tmux
          - zsh
          - sudo
          - docker.io
          - docker-compose
          - python3-docker
          - python3-pip
          - resolvconf
        state: present
        update_cache: true

    - name: Install docker compose
      ansible.builtin.pip:
        name:
          - docker-compose
        state: present

    - name: Enable UFW systemd
      ansible.builtin.systemd:
        name: ufw.service
        state: started
        enabled: true

    - name: Enable Docker
      ansible.builtin.systemd:
        name: docker.service
        state: started
        enabled: true

    - name: Allow temporary general SSH access
      community.general.ufw:
        rule: allow
        port: ssh
        proto: tcp

    - name: Enable UFW
      community.general.ufw:
        state: enabled
        policy: deny

    - name: Set logging
      community.general.ufw:
        logging: 'on'

    - name: Add astr0n8t user
      ansible.builtin.user:
        name: astr0n8t
        comment: astr0n8t
        groups: sudo
        password: "{{ sculk_user_password_hash }}"
        shell: /bin/bash

    - name: Set authorized keys
      ansible.posix.authorized_key:
        user: astr0n8t
        state: present
        key: "{{ lookup('file', 'authorized_keys') }}"
        exclusive: true
