- hosts: all
  name: Harden SSH
  tags: [always]
  tasks:
    - name: Include vault vars
      ansible.builtin.include_vars:
        file: vault_vars.yml

    - name: Allow SSH through Wireguard
      community.general.ufw:
        rule: allow
        direction: in
        interface: wg0
        from_ip: any
        to_ip: 192.168.150.1/32
        port: 22
        proto: tcp

    - name: Revoke general SSH access
      community.general.ufw:
        rule: allow
        port: ssh
        proto: tcp
        delete: yes
